"""init

Revision ID: 0a220faa8141
Revises:
Create Date: 2024-01-30 21:25:38.722237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a220faa8141"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_mediawiki_account_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acrid", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("biography", sa.String(), nullable=True),
        sa.Column("discord_message_id", sa.Integer(), nullable=False),
        sa.Column("discord_channel_id", sa.Integer(), nullable=False),
        sa.Column("discord_guild_id", sa.Integer(), nullable=False),
        sa.Column("request_url", sa.String(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_resolved", sa.DateTime(), nullable=True),
        sa.Column("action", sa.Integer(), nullable=True),
        sa.Column("handled_by_id", sa.Integer(), nullable=True),
        sa.Column("handled_by_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discord_mediawiki_account_requests")
    # ### end Alembic commands ###
