"""phpbb table

Revision ID: 60cdccb2bbcf
Revises: 0a220faa8141
Create Date: 2024-07-24 08:41:28.256095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60cdccb2bbcf"
down_revision: Union[str, None] = "0a220faa8141"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_phpbb_post_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("author_name", sa.String(), nullable=False),
        sa.Column("author_url", sa.String(), nullable=False),
        sa.Column("forum_name", sa.String(), nullable=False),
        sa.Column("forum_url", sa.String(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("post_ip_address", sa.String(), nullable=False),
        sa.Column("post_ip_hostname", sa.String(), nullable=True),
        sa.Column("post_ip_location", sa.String(), nullable=True),
        sa.Column("post_ip_organization", sa.String(), nullable=True),
        sa.Column("post_text", sa.String(), nullable=True),
        sa.Column("post_time", sa.DateTime(), nullable=False),
        sa.Column("topic_name", sa.String(), nullable=False),
        sa.Column("topic_url", sa.String(), nullable=False),
        sa.Column("user_group_list", sa.String(), nullable=False),
        sa.Column("user_join_date", sa.DateTime(), nullable=False),
        sa.Column("user_post_count", sa.Integer(), nullable=False),
        sa.Column("user_warning_count", sa.Integer(), nullable=False),
        sa.Column("is_for_new_topic", sa.Integer(), nullable=False),
        sa.Column("discord_message_id", sa.Integer(), nullable=False),
        sa.Column("discord_channel_id", sa.Integer(), nullable=False),
        sa.Column("discord_guild_id", sa.Integer(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_resolved", sa.DateTime(), nullable=True),
        sa.Column("action", sa.Integer(), nullable=True),
        sa.Column("handled_by_id", sa.Integer(), nullable=True),
        sa.Column("handled_by_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discord_phpbb_post_requests")
    # ### end Alembic commands ###
