"""add automod_disabled field

Revision ID: 9bac48f89f7f
Revises: 42fd072da194
Create Date: 2025-07-31 20:37:13.008546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bac48f89f7f"
down_revision: Union[str, None] = "42fd072da194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discord_mediawiki_account_requests",
        sa.Column("automod_disabled", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discord_mediawiki_account_requests", "automod_disabled")
    # ### end Alembic commands ###
