name: Run tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    strategy:
      matrix:
        python_version:
          - 3.10.16
          - 3.11.11
          - 3.12.8
          - 3.13.1

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Update pip and uv
        run: |
            pip install --upgrade pip -q
            pip install --upgrade uv -q

            uv venv

            source .venv/bin/activate

            echo PATH=$PATH >> $GITHUB_ENV

      - name: Install dependencies
        run:
            uv sync --frozen -q

      - name: Run flake8
        run: uv run flake8

      - name: Run ruff check
        run: uv run ruff check

      - name: Run ruff format
        run: uv run ruff format --diff

      - name: Run tests
        run: |
          uv run coverage run
          uv run coverage report
